### ISSUE TITLE
wifi.sh: Failed to bring up wlan0

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Distribution_MiSTer#31]
This error is sometimes emitted by `wifi.sh`:

![098F2DC4-49E5-48B2-83B5-2E57CC9F043E](https://user-images.githubusercontent.com/24398884/153960267-8ca568b0-3eb6-4c3d-b453-cdb1ec625600.jpeg)

It's not clear to a casual user what this means or what they are supposed to do about it.  It's also weird to see that error not displayed inside of a proper messagebox or dialog like the rest of the UI produced by the script.

The script should handle this case in a more user-friendly way.  Ideally, it would even provide common troubleshooting suggestions when this happens.

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/Scripts_MiSTer/blob/master/other_authors/wifi.sh

This is just the distribution repo. You should probably open an issue in Scripts_MiSTer for it instead. Failed to bring up wlan0 is a message from the linux system itself when you cannot successfully enable a connection. A catch for this error message and then a dialog box in the middle of the screen would have to be made.

**Comment by theypsilon** [comment]
@birdybro is right, closing.
