### ISSUE TITLE
Prevent "Game and Watch" from installing and updating

### ISSUE THREAD

**Issue by vanfanel** [MiSTer-devel/Distribution_MiSTer#36]
Hi!

For a month or so, I have had the "Game & Watch" core installed when running update_all.
So, as I do with other systems I am not interested in, I added `!gamenwatch` to the filter list in `downloader.ini`.
It works for a myriad of other systems, but doesn't seem to work for Game and Watch.
Am I doing something wrong?
Thanks!

**Comment by birdybro** [comment]
Try !GnW instead.

**Comment by vanfanel** [comment]
> Try !GnW instead.

That did the trick! Thanks!
