### ISSUE TITLE
GitHub actions make pull requests difficult/impossible to review

### ISSUE THREAD

**Issue by Kreeblah** [MiSTer-devel/Distribution_MiSTer#38]
I submitted https://github.com/MiSTer-devel/Distribution_MiSTer/pull/37 a little while ago and just this morning got a couple e-mails saying that it was closed because it was too big.  I was pretty confused about that, since the actual change I made that I was hoping to contribute was https://github.com/MiSTer-devel/Distribution_MiSTer/pull/37/commits/ef951c6b9f668b5f4db2a110ec8e57c551b617f9 which is a simple ten-line change in one file.

However, it seems that the GitHub actions in this project have run a number of times since, which have ended up somehow impacting the number of files included in the pull request.  I can't blame the reviewer for not wanting to review a 5,000+ file request, because that's just not reasonable to do, but I'm also at a loss as to what the right way to go about submitting changes to this repository is.

Since the GitHub actions seem to impact submitted pull requests, what's the right way to go about contributing potential changes here?

**Comment by theypsilon** [comment]
Sorry for the inconvenience. This repository is only for file distribution. No PRs to the main branch will be accepted. What content actually goes to main depends on the other repositories of this organization, there is where you should target your PRs. I'll try to add a comment about this to the README file to avoid further confusion.

There is a development branch for the content collection. Is fine to send PRs there but they should only modify the content collection scripts that are being used by the workflows.

Hope all is clear now.
