### ISSUE TITLE
Update Cave MRA to add rotation

### ISSUE THREAD

**Issue by capitaineflam25** [MiSTer-devel/Distribution_MiSTer#42]
Cave MRAs from https://github.com/MiSTer-devel/Arcade-Cave_MiSTer/tree/main/mra have been updated 3 months ago.

It would be nice to update also here so downloader get the latest files.
By having the correct rotation information it helps the OSD to be nicely rotated.

I'd like to help if i can do something.
![image](https://user-images.githubusercontent.com/985702/206271289-0bde193b-00ea-4a24-9a5c-d4f465b14b20.png)

**Comment by Toryalai1** [comment]
Once @nullobject has accepted my pull request in the Cave repo, the distribution will be updated as well. You can close this ticket :)

**Comment by capitaineflam25** [comment]
Thanks a lot !

**Comment by nullobject** [comment]
This has been merged, thanks for the PR @Toryalai1.
