### ISSUE TITLE
New core got picked up, then disappeared again

### ISSUE THREAD

**Issue by eriks5** [MiSTer-devel/Distribution_MiSTer#47]
This morning I released the C128 core. Added it to the Wiki so this repo would pick it up.

It took a few hours, but eventually the core was included in the distribution. But now it's gone again and looking at the output of the actions, the `download_distribution.py` script doesn't see it anymore. 

Here's the output the action that did see the new core: https://github.com/MiSTer-devel/Distribution_MiSTer/actions/runs/4263488131/jobs/7420287698

but later ones do not see it anymore. If I run `download_distribution.py` locally, the core is seen and processed.

I suspect there is some caching of the wiki page happening. Maybe on the builders, or maybe within GitHub's infrastructure.

**Comment by eriks5** [comment]
Created a pull request (#48) that adds no-cache headers and a cache-buster query parameter to the url. If it's a caching issue, that should fix it

**Comment by theypsilon** [comment]
Hey @eriks5 , thanks a lot for your contributions. I just merged your PR, hopefully this prevents that issue. Please, let me know if that's not the case.
