### ISSUE TITLE
Graphical bugs

### ISSUE THREAD

**Issue by Eebobobo** [MiSTer-devel/Distribution_MiSTer#52]
Hi all. 

Anyone having graphical issues with this game? Very early on I'm getting massive graphical corruption including sprites getting stuck and just appearing all over the place etc. which that then tanks the frame rate to the point of it running at about 1FPS. Sometimes I have to restart the game and hope it's okay, but that doesn't always work. 

I've attached a couple of screenshots. 

I wanted at attach a video but don't currently have time it edit it down to under 10MB. I'll upload a video to YouTube in a little while and send a link. 
![IMG_6661](https://github.com/MiSTer-devel/Distribution_MiSTer/assets/115956870/58be8c08-0549-4cae-8c30-752ed8ab642c)
![IMG_6662](https://github.com/MiSTer-devel/Distribution_MiSTer/assets/115956870/dcb09862-46cb-4ddc-8053-3e0223054a3f)

**Comment by Eebobobo** [comment]
https://www.youtube.com/watch?v=2PXdcmQoHg0

**Comment by Eebobobo** [comment]
Could someone delete this topic please? Don't know how it ended up in here. I've re-posted in the M92 section.

**Comment by Toryalai1** [comment]
Just click on close issue button

**Comment by Eebobobo** [comment]
> Just click on close issue button

Thanks =]
