### ISSUE TITLE
bug report: 280Z-ZZAP (US) does not respond to directions key bindings

### ISSUE THREAD

**Issue by goofyseeker311** [MiSTer-devel/Distribution_MiSTer#55]
cant actually play the game, even if its loads and coin button works. mame files are present.
left-right-up-down does nothing. not even numlock changing which joystick as input.

**Comment by goofyseeker311** [comment]
same goes for "Clowns" arcade game. not to keyboard bound joystick or to a real joystick.

**Comment by goofyseeker311** [comment]
keyboard/joystick interface does not work properly for country club.

**Comment by goofyseeker311** [comment]
keyboard (d-pad) does nothing in freeze, joystick works.

**Comment by goofyseeker311** [comment]
all cores forget joystick button definitions even if saved.

**Comment by goofyseeker311** [comment]
also for arcade cores, why timing settings is not 60Hz by default, usually its 55Hz or 57Hz.
mister outputs 60Hz by default.

**Comment by goofyseeker311** [comment]
jailbreak arcade core is graphically broken.

**Comment by goofyseeker311** [comment]
laguna racer does not respond to any kind of bound input (keyboard, joystick).

**Comment by goofyseeker311** [comment]
in some arcade cores having mouse connected will override/disable keyboard/joystick controls, like with marble madness.

**Comment by goofyseeker311** [comment]
megumi rescue does not respond to keyboard/joystick movement controls.

**Comment by goofyseeker311** [comment]
Mister Viking arcade core jams sometimes after 30-60s in game play.

**Comment by goofyseeker311** [comment]
some arcade game cores are not using the mame v0.263 zip file names.

**Comment by goofyseeker311** [comment]
bug report: ninja baseball bat man arcade code loses video signal at the first boss.

**Comment by goofyseeker311** [comment]
nova2001 crashes if you put 3 or more coins in.
also joystick/game-pad coin buttons resets the core.

**Comment by goofyseeker311** [comment]
packrats arcade core has crackling audio at times.

**Comment by goofyseeker311** [comment]
r-type leo arcade core gameplay jams about after 4mins, freezing graphics and game logic,
displaying 07 with some arrow on the screen bottom.

**Comment by goofyseeker311** [comment]
shuffleboard does not have a start button. ie cant play the game.

**Comment by goofyseeker311** [comment]
when pressing reset from the f12 osd menu, does not reset the credits or even game play.

**Comment by goofyseeker311** [comment]
super xevious arcade core will not run even if the correct 50, 51, 54 and sxevious files are present.

**Comment by goofyseeker311** [comment]
superior soldiers arcade core hangs graphically and logically after first win while music stays playing.

**Comment by goofyseeker311** [comment]
undercover cops arcade core graphically and sometimes logically jams after about 20-40seconds after starting a game.

**Comment by goofyseeker311** [comment]
air assault had some first time setup, running issues, messed up sprites and flipped screen, in vrt mode.
still has after some minutes of proper functioning.

**Comment by Toryalai1** [comment]
The issues you have listed here is not relevant to this repo and instead should be reported in each core repos. Please close this ticket

**Comment by goofyseeker311** [comment]
I dont know which main cores the cores are associated. do you prefer not reporting errors at all.

**Comment by Toryalai1** [comment]
> I dont know which main cores the cores are associated. do you prefer not reporting errors at all. maybe make a general feedback issues section for mister if you dont like me reporting here. can you take up the feedback and incorporate it to the cores or just copy paste the feedback.
> 
> edit: I dont think you appreciate any feedback on the issues.

There must be a language barrier here. What I was requesting you to do is create tickets in the core repos instead. The reason is because then the core developers will be able to see it. 

If you go here: https://github.com/MiSTer-devel, then search for the core, then create issue

My previous comment has nothing to do with not appreciating feedback, but rather, helping you lol

**Comment by goofyseeker311** [comment]
you are the barrier. if you check, every issue I reported here, does not have a named core, but a generic IREM or something core. I dont want to search in every IREM* core what cores they run.

**Comment by goofyseeker311** [comment]
I mean, before you condemn and try to help, why dont you test your own advice first. in this care it would not have worked.
