### ISSUE TITLE
calculate_db.py doesn't add empty zips section

### ISSUE THREAD

**Issue by zakk4223** [MiSTer-devel/Distribution_MiSTer#8]
If you run calculate_db.py against a repo/directory that results in there being no entries for the 'zips' section, it should add an empty section so the database file is compliant.

**Comment by theypsilon** [comment]
Thanks, that is fixed now. Btw, check the new preview of the custom database documentation, two new fields will be be mandatory soon 'timestamp' and 'default_options': https://github.com/theypsilon/Downloader_MiSTer/blob/main/docs/custom-databases.md
