### ISSUE TITLE
Missing a some of scripts

### ISSUE THREAD

**Issue by solskogen** [MiSTer-devel/Distribution_MiSTer#9]
The new downloader doesn't fetch a some of the scripts like the old updater.sh (it's missing bluetooth pairing for example)

**Comment by theypsilon** [comment]
This is intended, the base distribution will provide the minimum amount of scripts. 

Bluetooth pairing is now provided by the OS out of the box with the new Linux version, so it shouldn't be necessary anyways.

But in any case, if people would like to have more scripts, there is now a way to integrate them in the Downloader with custom databases: https://github.com/MiSTer-devel/Downloader_MiSTer/blob/main/docs/custom-databases.md

**Comment by birdybro** [comment]
>Bluetooth pairing is now provided by the OS out of the box with the new Linux version, so it shouldn't be necessary anyways.

I think adding this script is a good idea as this is only doable for someone with a keyboard attached or the OSD button installed on an IO board or manually installed DIY. If someone is doing setup with a wired gamepad then this is not the case and the script may still be useful for first time configuration.

**Comment by theypsilon** [comment]
@birdybro But how would you call the script on a first time setup without a keyboard anyways?

**Comment by birdybro** [comment]
> @birdybro But how would you call the script on a first time setup without a keyboard anyways?

Controllers already by default work when plugged in wired. And now thanks to Zakk's addition of gamecontroller-db many popular controllers work out of the box. So you could use one controller to pair a Bluetooth controller.
